web:
  build: .
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  environment:
    - FLASK_APP=app/main.py
    - FLASK_DEBUG=development
  links:
    - db
db:
  image: mongo
  ports:
    - "27017:27017"