from async_crawler.hrodna_life_async_crawler import HrodnaLifeAsyncCrawler
from async_crawler.navinyby_async_crawler import NavinybyAsyncCrawler
from async_crawler.tutby_async_crawler import TutbyAsyncCrawler
